//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructor
    {
        public string userID { get; set; }
        public string phoneNumber { get; set; }
        public string firstName { get; set; }
        public string LastName { get; set; }
        public string specialization { get; set; }
        public string position { get; set; }
        public Nullable<decimal> salary { get; set; }
    }
}
